### ISSUE TITLE
Exception when try to click on "Configure settings" after enable the module

### ISSUE THREAD

**Issue by p4535992** [VTTAssets/vtta-tokenizer#14]
Foundry version: 0.6.1
System Settings : D&D 5th 0.92
Module version: 2.1.3

After enable the module i can't edit the "configure settings" panel because of a exception.
Here a image of the exception:
![error](https://i.imgur.com/nbLuKc2.png)

Greetings.

**Comment by VTTAssets** [comment]
This is fixed in 2.2.0 (publishing now)
