### ISSUE TITLE
Cannot edit tokenizer token/avatar

### ISSUE THREAD

**Issue by renkhal** [VTTAssets/vtta-tokenizer#17]
![tokenizer screen](https://user-images.githubusercontent.com/67495904/85915427-7b427b80-b815-11ea-8672-d1827b348827.jpg)

I just updated Foundry VTT to 0.6.4 and Tokenizer to 2.2.1, and this is what I'm seeing when I click to change an avatar and thus also the token. I've tried restarting Foundry, uninstalling and then reinstalling tokenizer, and we had just had to do a fresh reinstall of Foundry (which we realized messed up some of our tokens since they weren't in the right place because they hadn't been made with tokenizer).

**Comment by Daostorm** [comment]
Hey, I am having a similar problem as well, although I realized that this problem occurred when I decided to change the avatar/token art directory from default to a custom location.

I am able to make new character avatars and tokens just fine, but the older PC sheets look like what you posted as well.

**Comment by VTTAssets** [comment]
This is the behaviour when the images are not found where they should be, e.g. if you moved the images to a new destination. 

Hold shift when clicking on the avatar to bring up the regular file dialog. Use that dialog to set the image from the new location. Tokenizer will be working as usual after you have set a correct image.

Note: This is not necessarily a buggy behaviour. If you move an image to a new directory, all links to the previous URL break, that is common when using web technology (and Foundry is basically a webserver).
