### ISSUE TITLE
BUG - Can't update module settings for any module on Foundry VTT 0.7.2 when the module is enable

### ISSUE THREAD

**Issue by p4535992** [VTTAssets/vtta-tokenizer#20]
**Environment Details:**

Foundry VTT Version: 0.7.2
Operating System: [Linux]
How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]
Which Game System: Dungeons and Dragons 5th Edition, version 0.96
Modules Enabled?: yes
OS, Hosting, Browser (if applicable): Linux/Node/Chrome
Module Version : 2.2.1

**Description of the issue:**

After update to foundry 0.7.2 i'm getting this error when i try to save the modules settings.

**Uncaught (in promise) TypeError: Failed to construct 'Image': Please use the 'new' operator, this DOM object constructor cannot be called as a function.**

![img](https://i.imgur.com/TaSC7rN.png)

it looks like ExtendedSettingsConfig is the cause.

**Comment by VTTAssets** [comment]
Can confirm, thanks. Foundry changed the way it registers the settings and I had to rename the config type from Image to ImageUrl. Fixed in the next release.
