### ISSUE TITLE
Mask Works Poorly with Partial Transparency

### ISSUE THREAD

**Issue by kevincox** [VTTAssets/vtta-tokenizer#25]
The mask algorithm seems to only mask at total transparency. The problem is that a lot (maybe most) images have some sort of dither or fade at the border to blend in better with the background (or provide a transparent shadow). 

<img width="410" alt="image" src="https://user-images.githubusercontent.com/494012/96721604-5bae0080-137a-11eb-9c55-07d5ba3a220a.png">

For many images it is probably better to mask out anywhere that there is partial transparency on the outside edge. However the inside edge would want to use the current logic still.

**Comment by nathonius** [comment]
Came here to raise this exact issue with this exact image as well. Glad someone else wants to use _the_ token border. For now this means i'll keep using tokenstamp.

Even if partial transparency was left as is, maybe a circular mask layer? Or per-layer masking.

**Comment by VTTAssets** [comment]
Vtta-tokenizer is deprecated and replaced by vtta-tokens, which uses a rewritten algorithm that addresses this issue specifically.

**Comment by nathonius** [comment]
Welcome back. 😃 Linking the new module (does not yet seem available for install) for anyone looking at this issue in the future: https://github.com/VTTAssets/vtta-tokens
